---
title: "Questionnaire Data"
author: "Adeline Shin"
date: "3/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(nhanesA)
```

# Extracting Demographic Data
```{r}
demographic_full_df = nhanes("DEMO_I") %>% 
  janitor::clean_names()

# Selecting categorical variables separately to replace unknown values with NAs
demographic_partial = demographic_full_df %>% 
  select(seqn, riagendr, ridreth1, ridreth3, dmdborn4, dmdeduc3, dmdeduc2, indfmin2) %>%
  mutate(
    riagendr = as.factor(riagendr),
    ridreth1 = as.factor(ridreth1),
    ridreth3 = as.factor(ridreth3),
    dmdborn4 = as.factor(dmdborn4),
    dmdeduc3 = as.factor(dmdeduc3),
    dmdeduc2 = as.factor(dmdeduc2),
    indfmin2 = as.factor(indfmin2)
  ) %>% 
  na_if(., 99) %>% 
  na_if(., 77) %>% 
  na_if(., ".")

# Selecting all responses from adults
demographic_age = demographic_full_df %>% 
  select(seqn, ridageyr) %>% 
  filter(ridageyr > 17)

# Joining demographic data into one dataset
demographic_df = left_join(demographic_age, demographic_partial, by = "seqn")

# Write data to a csv for easier access later
write.csv(demographic_df, "./demographic_data.csv")
```

# Extracting Questionnaire Data
```{r}
# Extract Particular Answers from different Datasets
bp_cholesterol_df = nhanes("BPQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, bpq020)

cv_health_df = nhanes("CDQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, cdq001)

consumer_behavior_df = nhanes("CBQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, cbd071, cbd121, cbd131)

health_status_df = nhanes("HSQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, hsd010)

diabetes_df = nhanes("DIQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, diq010)

diet_behavior_df = nhanes("DBQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, dbq700, dbd895)

food_security_df = nhanes("FSQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, fsd032a, fsd032c, fsdhh)

insurance_df = nhanes("HIQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, hiq011, hiq270)

activity_df = nhanes("PAQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, paq605)

smoking_df = nhanes("SMQ_I") %>% 
  janitor::clean_names() %>% 
  select(seqn, smq020)

# Combining data into full questionnaire dataframe
questionnaire_full_df = full_join(bp_cholesterol_df, cv_health_df, by = "seqn")
questionnaire_full_df = full_join(questionnaire_full_df, consumer_behavior_df, by = "seqn")
questionnaire_full_df = full_join(questionnaire_full_df, health_status_df, by = "seqn")
questionnaire_full_df = full_join(questionnaire_full_df, diabetes_df, by = "seqn")
questionnaire_full_df = full_join(questionnaire_full_df, diet_behavior_df, by = "seqn")
questionnaire_full_df = full_join(questionnaire_full_df, food_security_df, by = "seqn")
questionnaire_full_df = full_join(questionnaire_full_df, insurance_df, by = "seqn")
questionnaire_full_df = full_join(questionnaire_full_df, activity_df, by = "seqn")
questionnaire_full_df = full_join(questionnaire_full_df, smoking_df, by = "seqn")

questionnaire_numerical = questionnaire_full_df %>% 
  select(seqn, cbd071, cbd121, cbd131, dbd895) %>% 
  na_if(., 777777) %>% 
  na_if(., 999999) %>% 
  na_if(., ".") %>% 
  na_if(., 7777) %>% 
  na_if(., 9999)

questionnaire_categorical = questionnaire_full_df %>% 
  select(seqn, bpq020, cdq001, hsd010, diq010, dbq700, fsd032a, fsd032c, fsdhh, hiq011, hiq270, paq605, smq020) %>% 
  mutate(
    bpq020 = as.factor(bpq020),
    cdq001 = as.factor(cdq001),
    hsd010 = as.factor(hsd010),
    diq010 = as.factor(diq010),
    dbq700 = as.factor(dbq700),
    fsd032a = as.factor(fsd032a),
    fsd032c = as.factor(fsd032c),
    fsdhh = as.factor(fsdhh),
    hiq011 = as.factor(hiq011),
    hiq270 = as.factor(hiq270),
    paq605 = as.factor(paq605),
    smq020 = as.factor(smq020)
  ) %>% 
  na_if(., 7) %>% 
  na_if(., 9) %>% 
  na_if(., ".")
  
# Combining the categorical and numerical portions
questionnaire_full_df = full_join(questionnaire_numerical, questionnaire_categorical, by = "seqn")

# Write the data to a csv for easier access later
write.csv(questionnaire_full_df, "./questionnaire_data.csv")
```

