---
title: "dietary_data_extraction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("nhanesA")
library(tidyverse)
library(nhanesA)
```


### Brings you to NHANES website page (not actual data)

```{r}
#browseNHANES(year = 2016, data_group = "DIET")
```

### Pulling "Dietary Interview - Total Nutrient Intakes, First Day" & "Dietary Supplement Use 24-Hour - Total Dietary Supplements, First Day" Tables

```{r}
nutrients_full_df <- nhanes('DR1TOT_I')

supplements_full_df <- nhanes('DS1TOT_I')
```

### Tidying Nutriets Dataframe

```{r}
nutrients_selected_df <- nutrients_full_df %>% 
  select("SEQN", "DBD100", "DRQSPREP", "DRQSDIET", "DR1TNUMF", "DR1TKCAL", "DR1TPROT", "DR1TCARB", "DR1TSUGR", "DR1TFIBE", "DR1TTFAT", "DR1TCAFF", "DR1TALCO", "DR1.300", "DR1.320Z", "DR1.320Z", "DRD340", "DRD360") %>% 
  mutate(
    DBD100 = as.factor(DBD100),
    DRQSPREP = as.factor(DRQSPREP),
    DRQSDIET = as.factor(DRQSDIET),
    DR1.300 = as.factor(DR1.300),
    DRD340 = as.factor(DRD340),
    DRD360 = as.factor(DRD360)
  ) %>% 
  mutate(
    DBD100 = na_if(DBD100,"9"), 
    DRQSPREP = na_if(DRQSPREP, "9"),
    DRQSDIET = na_if(DRQSDIET, "9"), 
    DR1.300 = na_if(DR1.300, "7"),
    DR1.300 = na_if(DR1.300, "9"), 
    DRD340 = na_if(DRD340, "7"),
    DRD340 = na_if(DRD340, "9"),
    DRD360 = na_if(DRD360, "7"),
    DRD360 = na_if(DRD360, "9")
  )
```

### Tidying Supplements Dataframe

```{r}
supplements_selected_df <- supplements_full_df %>% 
  select("SEQN", "DS1DSCNT", "DS1ANCNT")
```

