---
title: "0.75 Elastic Net and 632 Bootstrap"
author: "Adeline Shin"
date: "4/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn = -1)
library(tidyverse)
library(caret)
library(ModelMetrics)
library(glmnet)
library(bootstrap)
```

# Loading the Data
```{r}
training_data = read_csv("./training_data_final.csv")
test_data = read_csv("./test_data_final.csv")

y = training_data$lbdldl
x = model.matrix(lbdldl ~ ., training_data)[, -(1:2)]
y_test = test_data$lbdldl
x_test = model.matrix(lbdldl ~ ., test_data)[, -(1:2)]
```

# Model Creation using Elastic Net with 10-fold CV
```{r}
set.seed(13)
ctrl1 = trainControl(method = "repeatedcv", number = 10, repeats = 5)

elastic_net_fit = train(lbdldl ~ .,
                        data = training_data,
                        method = "glmnet",
                        tuneGrid = expand.grid(alpha = 0.75, 
                                          lambda = exp(seq(-0, 2, length=100))),
                        preProc = c("center", "scale"),
                        trControl = ctrl1)

plot(elastic_net_fit)

elastic_net_coef = coef(elastic_net_fit$finalModel, elastic_net_fit$bestTune$lambda)
sum_coef = sum(as.vector(elastic_net_coef) != 0)
```

As shown on the graph above, the value of lambda that gives the lowest RMSE value is `r elastic_net_fit$bestTune$lambda`.

# Prediction using Elastic Net model
```{r}
elastic_net_prediction = predict(elastic_net_fit, newdata = test_data)
elastic_net_mse = mse(y_test, elastic_net_prediction)
```

# Same but with 632 bootstrap validation
```{r}
set.seed(13)
ctrl2 = trainControl(method = "boot632")

elastic_net_fit_2 = train(lbdldl ~ .,
                          data = training_data,
                          method = "glmnet",
                          tuneGrid = expand.grid(alpha = 0.75, 
                                            lambda = exp(seq(-0, 2, length=100))),
                          preProc = c("center", "scale"),
                          trControl = ctrl2)

plot(elastic_net_fit_2)
```

# Prediction using Elastic Net with 632 Bootstrap
```{r}
prediction_632 = predict(elastic_net_fit_2, newdata = test_data)
mse_632 = mse(y_test, prediction_632)
```

